from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

# Testando o endpoint root
def test_read_root():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "API para consulta de dados CSV da Embrapa"}

# Testando o endpoint que retorna todos os CSVs
def test_get_all_csv_data():
    response = client.get("/csv_data/", headers={"Authorization": "Bearer test_token"})
    assert response.status_code == 200
    assert isinstance(response.json(), dict)
    # Checar se os arquivos CSV estão presentes
    for i in range(1, 6):
        assert f"arquivo_{i}" in response.json()

# Testando o endpoint que retorna um CSV específico
def test_get_csv_by_id():
    response = client.get("/csv_data/1", headers={"Authorization": "Bearer test_token"})
    assert response.status_code == 200
    assert isinstance(response.json(), list)  # Deveria retornar uma lista de registros

# Testando o endpoint para ler um CSV local
def test_get_local_csv():
    response = client.get("/local_csv/Producao.csv", headers={"Authorization": "Bearer test_token"})
    if response.status_code == 200:
        assert isinstance(response.json(), list)  # Se o arquivo existe, ele deve retornar uma lista de registros
    else:
        assert response.status_code == 404  # Se o arquivo não existe, deve retornar 404
